const persons = [
  {
    personal_Id: "1",
    firstname: "Thomas",
    lastname: "Müller",
    role: "dev",
  },
  {
    personal_Id: "2",
    firstname: "Jarno",
    lastname: "Recklinghausen",
    role: "dev",
  },
  {
    personal_Id: "3",
    firstname: "Simone",
    lastname: "Winterberg",
    role: "dev",
  },
  {
    personal_Id: "4",
    firstname: "Andrea",
    lastname: "See",
    role: "dev",
  },
  {
    personal_Id: "5",
    firstname: "Reiko",
    lastname: "Mann",
    role: "bc",
  },
  {
    personal_Id: "6",
    firstname: "Carmen",
    lastname: "Müller",
    role: "bc",
  },
  {
    personal_Id: "7",
    firstname: "Laura",
    lastname: "Hammer",
    role: "bc",
  },
  {
    personal_Id: "8",
    firstname: "Thorsten",
    lastname: "Kurz",
    role: "bc",
  },
  {
    personal_Id: "9",
    firstname: "Sebastian",
    lastname: "Brucker",
    role: "bc",
  },
  {
    personal_Id: "10",
    firstname: "Jochen",
    lastname: "Maier",
    role: "bc",
  },
  {
    personal_Id: "11",
    firstname: "Helmut",
    lastname: "Schön",
    role: "bc",
  },
  {
    personal_Id: "12",
    firstname: "Veit",
    lastname: "Maurer",
    role: "dev",
  },
  {
    personal_Id: "13",
    firstname: "Ahmet",
    lastname: "Peros",
    role: "bc",
  },
  {
    personal_Id: "14",
    firstname: "Thorsten",
    lastname: "Kurz",
    role: "bc",
  },
  {
    personal_Id: "15",
    firstname: "Reiko",
    lastname: "Carlsen",
    role: "bc",
  },
  {
    personal_Id: "16",
    firstname: "Maria",
    lastname: "Angstmann",
    role: "bc",
  },
  {
    personal_Id: "17",
    firstname: "Stefan",
    lastname: "Hirtel",
    role: "dev",
  },
  {
    personal_Id: "18",
    firstname: "August",
    lastname: "Keller",
    role: "bc",
  },
  {
    personal_Id: "19",
    firstname: "Heidrun",
    lastname: "Maier",
    role: "bc",
  },
  {
    personal_Id: "20",
    firstname: "Andrea",
    lastname: "Meier",
    role: "bc",
  },
  {
    personal_Id: "21",
    firstname: "Diana",
    lastname: "Carosi",
    role: "bc",
  },
  {
    personal_Id: "22",
    firstname: "Luka",
    lastname: "Ambrosius",
    role: "dev",
  },
  {
    personal_Id: "23",
    firstname: "Serkan",
    lastname: "Turhan",
    role: "bc",
  },
  {
    personal_Id: "24",
    firstname: "Sergej",
    lastname: "Seehl",
    role: "dev",
  },
  {
    personal_Id: "25",
    firstname: "Thomas",
    lastname: "Bauernfeind",
    role: "bc",
  },
];

export default persons;
