const solutions = [
  {
    solution_Id: "1",
    solution: "Einkauf",
    team: "AA",
    bpe: ["9"],
    bseint: ["10"],
    bsegr: ["11"],
    leadDeveloper: ["12"],
    cbo: ["13"],
    supportGroup: "supp-einkauf",
    modules: ["1", "2", "3"],
  },
  {
    solution_Id: "2",
    solution: "Controlling",
    team: "TX",
    bpe: ["14"],
    bseint: ["15"],
    bsegr: ["16"],
    leadDeveloper: ["17"],
    cbo: ["18"],
    supportGroup: "supp-controlling",
    modules: ["4", "5", "6"],
  },
  {
    solution_Id: "3",
    solution: "Verkauf",
    team: "AA",
    bpe: ["19"],
    bseint: ["20"],
    bsegr: ["21"],
    leadDeveloper: ["22"],
    cbo: ["23"],
    supportGroup: "supp-verkauf",
    modules: ["7", "8", "9"],
  },
  {
    solution_Id: "4",
    solution: "Verwaltung",
    team: "AA",
    bpe: ["9"],
    bseint: ["15"],
    bsegr: ["21"],
    leadDeveloper: ["24"],
    cbo: ["25"],
    supportGroup: "supp-verwaltung",
    modules: ["10"],
  },
];

export default solutions;
